# Generated by Django 5.2.17 on 2026-08-18 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(default='Gemeinsames Schiff', max_length=120)),
                ('values', models.JSONField(default=dict)),
                ('field_versions', models.JSONField(default=dict)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=120)),
                ('values', models.JSONField(default=dict)),
                ('field_versions', models.JSONField(default=dict)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SheetChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=120)),
                ('old_value', models.JSONField(null=True)),
                ('new_value', models.JSONField(null=True)),
                ('resulting_version', models.PositiveBigIntegerField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_changes', to=settings.AUTH_USER_MODEL)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='sheets.charactersheet')),
                ('ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='sheets.shipsheet')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('character__isnull', False), ('ship__isnull', True)), models.Q(('character__isnull', True), ('ship__isnull', False)), _connector='OR'), name='sheetchange_exactly_one_target')],
            },
        ),
    ]
