# Generated by Django 5.2.17 on 2026-10-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginthrottle_user_is_portal_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginthrottle',
            name='window_started_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
