"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import secrets
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

# Placeholder/example secrets that must never reach a production deployment.
# ".env.example" ships one of these on purpose so an operator who forgets to
# change it gets a hard failure instead of a silently insecure site.
_WEAK_SECRET_KEYS = {
    "change-me",
    "changeme",
    "secret",
    "insecure",
    "replace-with-a-long-random-secret",
}
_MINIMUM_PRODUCTION_SECRET_LENGTH = 32

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = secrets.token_urlsafe(50)
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false"
        )
elif not DEBUG:
    _normalized_secret = SECRET_KEY.strip().lower()
    if (
        _normalized_secret in _WEAK_SECRET_KEYS
        or _normalized_secret.startswith("django-insecure-")
        or len(SECRET_KEY) < _MINIMUM_PRODUCTION_SECRET_LENGTH
    ):
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be a strong, non-default secret "
            "(at least 32 characters) when DJANGO_DEBUG is false"
        )

# ALLOWED_HOSTS must be provided explicitly in production. The
# 127.0.0.1/localhost fallback below is only safe for local development.
_allowed_hosts_env = os.environ.get("DJANGO_ALLOWED_HOSTS")
if not DEBUG and not _allowed_hosts_env:
    raise ImproperlyConfigured(
        "DJANGO_ALLOWED_HOSTS must be set explicitly when DJANGO_DEBUG is false"
    )
ALLOWED_HOSTS = (_allowed_hosts_env or "127.0.0.1,localhost").split(",")

PUBLIC_BASE_URL = os.environ.get("PUBLIC_BASE_URL", "http://127.0.0.1:8000")
APP_BIND_ADDRESS = os.environ.get("APP_BIND_ADDRESS", "127.0.0.1")

# The portal always sits behind a reverse proxy that terminates TLS and
# forwards the original scheme via X-Forwarded-Proto, so Django needs to
# trust that header to know a request was actually secure.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# CSRF_TRUSTED_ORIGINS must include the scheme (e.g. "https://example.com"),
# which PUBLIC_BASE_URL already carries.
CSRF_TRUSTED_ORIGINS = [PUBLIC_BASE_URL]

# Clickjacking / MIME-sniffing protections apply regardless of DEBUG -- they
# do not interfere with local development.
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True

# Cookie/transport security is only forced on in production so that plain
# HTTP development (DJANGO_DEBUG=1, no TLS-terminating proxy) keeps working.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG

# HTTP Strict Transport Security is opt-in via ENABLE_HSTS=1 so it can only
# be turned on once the reverse proxy is confirmed to serve HTTPS correctly
# -- an incorrect HSTS header cannot be easily undone by clients.
ENABLE_HSTS = os.environ.get("ENABLE_HSTS", "0") == "1"
if ENABLE_HSTS:
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Technical errors are logged; nothing here logs request bodies, so
# passwords, session values, and sheet content are never captured.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "default",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'core',
    'sheets',
    'wiki',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.ForcePasswordChangeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get("DATABASE_PATH", BASE_DIR / "data" / "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"

LOGIN_URL = "/account/login/"

WIKI_CONTENT_ROOT = Path(os.environ.get("WIKI_CONTENT_ROOT", "/content/wiki"))

# Ordered, explicit filenames (not extensions) allowed to be loaded as wiki
# chapters. Anything not listed here -- e.g. the project's own progress log
# -- is excluded even if it lives under WIKI_CONTENT_ROOT.
WIKI_DEFAULT_CONTENT_ALLOWLIST = (
    "00-Foreword.md",
    "00-Inhaltsverzeichnis-und-Einleitung.md",
    "01-Charaktererschaffung.md",
    "02-Karrierewege.md",
    "03-Skills.md",
    "04-Talents.md",
    "05-Armoury.md",
    "06-Psychic-Powers.md",
    "07-Navigator-Powers.md",
    "08-Starships.md",
    "09-Playing-The-Game.md",
    "10-The-Game-Master.md",
    "11-The-Imperium.md",
    "12-Rogue-Traders.md",
    "13-The-Koronus-Expanse.md",
    "14-Adversaries-and-Aliens.md",
    "14-Allies-Enemies-and-Rivals.md",
    "14-Mutations.md",
    "14-Traits.md",
    "15-Into-The-Maw.md",
    "16-Index.md",
)
WIKI_CONTENT_ALLOWLIST = tuple(
    filename.strip()
    for filename in os.environ.get(
        "WIKI_CONTENT_ALLOWLIST", ",".join(WIKI_DEFAULT_CONTENT_ALLOWLIST)
    ).split(",")
    if filename.strip()
)
SHEET_SOURCE_PDF = Path(
    os.environ.get("SHEET_SOURCE_PDF", BASE_DIR / "data" / "character-sheet.pdf")
)
